services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17}
    container_name: ${POSTGRES_CONTAINER_NAME:-development-database}
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    ports:
      - "${DB_PORT:-0}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d/dumps:ro
      - ./init-scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./init-scripts/config.yml:/docker-entrypoint-initdb.d/config.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    

volumes:
  postgres_data: